# Generated by Django 3.0 on 2019-12-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stageproj', '0002_auto_20191203_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='editorUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stageproj.User'),
            preserve_default=False,
        ),
    ]
